version: '3.5'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /path/to/media
        target: /media
        read_only: true
    restart: 'unless-stopped'
    privileged: true
